import type { Organization, Profile } from '../../types/database.types'

// DEV-ONLY seed data: 7 demo organizations and 150 demo users, generated to
// exercise the central-control (platform) view. Not real tenant data.

const NOW = new Date().toISOString()

export const MOCK_ORGS: Organization[] = [
  { id: 'org-1', name: 'Lava Mobiles India', org_code: 'LAVA', logo_url: null, created_at: NOW, created_by: null },
  { id: 'org-2', name: 'Zenith Electronics Pvt Ltd', org_code: 'ZENITH', logo_url: null, created_at: NOW, created_by: null },
  { id: 'org-3', name: 'Nova Retail Distributors', org_code: 'NOVA', logo_url: null, created_at: NOW, created_by: null },
  { id: 'org-4', name: 'Orbit Mobility Solutions', org_code: 'ORBIT', logo_url: null, created_at: NOW, created_by: null },
  { id: 'org-5', name: 'Vertex Consumer Electronics', org_code: 'VERTEX', logo_url: null, created_at: NOW, created_by: null },
  { id: 'org-6', name: 'Prime Gadget Distribution', org_code: 'PRIME', logo_url: null, created_at: NOW, created_by: null },
  { id: 'org-7', name: 'Apex Mobile Networks', org_code: 'APEX', logo_url: null, created_at: NOW, created_by: null },
]

export const MOCK_USERS: Profile[] = [
  { id: 'user-1', org_id: 'org-1', employee_code: 'LAVA-ADM-001', full_name: 'Aditya Verma', role: 'admin', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-2', org_id: 'org-1', employee_code: 'LAVA-MGR-001', full_name: 'Ramesh Gupta', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-3', org_id: 'org-1', employee_code: 'LAVA-MGR-002', full_name: 'Meera Mehta', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-4', org_id: 'org-1', employee_code: 'LAVA-MGR-003', full_name: 'Sai Menon', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-5', org_id: 'org-1', employee_code: 'LAVA-REP-001', full_name: 'Krishna Menon', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-6', org_id: 'org-1', employee_code: 'LAVA-REP-002', full_name: 'Anika Iyer', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-7', org_id: 'org-1', employee_code: 'LAVA-REP-003', full_name: 'Sunita Malhotra', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-8', org_id: 'org-1', employee_code: 'LAVA-REP-004', full_name: 'Vinod Pillai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-9', org_id: 'org-1', employee_code: 'LAVA-REP-005', full_name: 'Reyansh Reddy', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-10', org_id: 'org-1', employee_code: 'LAVA-REP-006', full_name: 'Deepak Malhotra', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-11', org_id: 'org-1', employee_code: 'LAVA-REP-007', full_name: 'Ajay Desai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-12', org_id: 'org-1', employee_code: 'LAVA-REP-008', full_name: 'Amit Desai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-13', org_id: 'org-1', employee_code: 'LAVA-REP-009', full_name: 'Pooja Desai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-14', org_id: 'org-1', employee_code: 'LAVA-REP-010', full_name: 'Deepak Desai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-15', org_id: 'org-1', employee_code: 'LAVA-REP-011', full_name: 'Kavya Bhatt', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-16', org_id: 'org-1', employee_code: 'LAVA-REP-012', full_name: 'Rekha Sharma', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-17', org_id: 'org-1', employee_code: 'LAVA-REP-013', full_name: 'Sanjay Agarwal', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-18', org_id: 'org-1', employee_code: 'LAVA-REP-014', full_name: 'Kiran Agarwal', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-19', org_id: 'org-1', employee_code: 'LAVA-REP-015', full_name: 'Kavya Rao', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-20', org_id: 'org-1', employee_code: 'LAVA-REP-016', full_name: 'Ramesh Kapoor', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-21', org_id: 'org-1', employee_code: 'LAVA-REP-017', full_name: 'Ananya Agarwal', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-22', org_id: 'org-1', employee_code: 'LAVA-REP-018', full_name: 'Vikram Nair', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-23', org_id: 'org-2', employee_code: 'ZENITH-ADM-001', full_name: 'Swati Singh', role: 'admin', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-24', org_id: 'org-2', employee_code: 'ZENITH-MGR-001', full_name: 'Nisha Pillai', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-25', org_id: 'org-2', employee_code: 'ZENITH-MGR-002', full_name: 'Sai Gupta', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-26', org_id: 'org-2', employee_code: 'ZENITH-MGR-003', full_name: 'Meera Agarwal', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-27', org_id: 'org-2', employee_code: 'ZENITH-REP-001', full_name: 'Kavya Singh', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-28', org_id: 'org-2', employee_code: 'ZENITH-REP-002', full_name: 'Neha Kapoor', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-29', org_id: 'org-2', employee_code: 'ZENITH-REP-003', full_name: 'Divya Nair', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-30', org_id: 'org-2', employee_code: 'ZENITH-REP-004', full_name: 'Rekha Bhatt', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-31', org_id: 'org-2', employee_code: 'ZENITH-REP-005', full_name: 'Myra Chopra', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-32', org_id: 'org-2', employee_code: 'ZENITH-REP-006', full_name: 'Divya Joshi', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-33', org_id: 'org-2', employee_code: 'ZENITH-REP-007', full_name: 'Vikram Agarwal', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-34', org_id: 'org-2', employee_code: 'ZENITH-REP-008', full_name: 'Meera Chopra', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-35', org_id: 'org-2', employee_code: 'ZENITH-REP-009', full_name: 'Shalini Nair', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-36', org_id: 'org-2', employee_code: 'ZENITH-REP-010', full_name: 'Suresh Nair', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-37', org_id: 'org-2', employee_code: 'ZENITH-REP-011', full_name: 'Pooja Joshi', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-38', org_id: 'org-2', employee_code: 'ZENITH-REP-012', full_name: 'Shalini Chopra', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-39', org_id: 'org-2', employee_code: 'ZENITH-REP-013', full_name: 'Vinod Chopra', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-40', org_id: 'org-2', employee_code: 'ZENITH-REP-014', full_name: 'Ananya Chopra', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-41', org_id: 'org-2', employee_code: 'ZENITH-REP-015', full_name: 'Ajay Joshi', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-42', org_id: 'org-2', employee_code: 'ZENITH-REP-016', full_name: 'Ishita Kapoor', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-43', org_id: 'org-2', employee_code: 'ZENITH-REP-017', full_name: 'Vinod Desai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-44', org_id: 'org-2', employee_code: 'ZENITH-REP-018', full_name: 'Riya Rao', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-45', org_id: 'org-3', employee_code: 'NOVA-ADM-001', full_name: 'Reyansh Sharma', role: 'admin', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-46', org_id: 'org-3', employee_code: 'NOVA-MGR-001', full_name: 'Sai Kapoor', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-47', org_id: 'org-3', employee_code: 'NOVA-MGR-002', full_name: 'Rekha Mehta', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-48', org_id: 'org-3', employee_code: 'NOVA-MGR-003', full_name: 'Swati Patel', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-49', org_id: 'org-3', employee_code: 'NOVA-REP-001', full_name: 'Saanvi Agarwal', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-50', org_id: 'org-3', employee_code: 'NOVA-REP-002', full_name: 'Ananya Rao', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-51', org_id: 'org-3', employee_code: 'NOVA-REP-003', full_name: 'Krishna Sharma', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-52', org_id: 'org-3', employee_code: 'NOVA-REP-004', full_name: 'Amit Mehta', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-53', org_id: 'org-3', employee_code: 'NOVA-REP-005', full_name: 'Reyansh Menon', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-54', org_id: 'org-3', employee_code: 'NOVA-REP-006', full_name: 'Meera Rao', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-55', org_id: 'org-3', employee_code: 'NOVA-REP-007', full_name: 'Pooja Verma', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-56', org_id: 'org-3', employee_code: 'NOVA-REP-008', full_name: 'Pooja Menon', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-57', org_id: 'org-3', employee_code: 'NOVA-REP-009', full_name: 'Krishna Patel', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-58', org_id: 'org-3', employee_code: 'NOVA-REP-010', full_name: 'Pooja Agarwal', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-59', org_id: 'org-3', employee_code: 'NOVA-REP-011', full_name: 'Diya Desai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-60', org_id: 'org-3', employee_code: 'NOVA-REP-012', full_name: 'Neha Nair', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-61', org_id: 'org-3', employee_code: 'NOVA-REP-013', full_name: 'Riya Iyer', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-62', org_id: 'org-3', employee_code: 'NOVA-REP-014', full_name: 'Neha Gupta', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-63', org_id: 'org-3', employee_code: 'NOVA-REP-015', full_name: 'Amit Patel', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-64', org_id: 'org-3', employee_code: 'NOVA-REP-016', full_name: 'Kavya Iyer', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-65', org_id: 'org-3', employee_code: 'NOVA-REP-017', full_name: 'Sai Iyer', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-66', org_id: 'org-3', employee_code: 'NOVA-REP-018', full_name: 'Neha Nair', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-67', org_id: 'org-4', employee_code: 'ORBIT-ADM-001', full_name: 'Vihaan Rao', role: 'admin', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-68', org_id: 'org-4', employee_code: 'ORBIT-MGR-001', full_name: 'Aadhya Verma', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-69', org_id: 'org-4', employee_code: 'ORBIT-MGR-002', full_name: 'Ishaan Malhotra', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-70', org_id: 'org-4', employee_code: 'ORBIT-MGR-003', full_name: 'Rekha Kumar', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-71', org_id: 'org-4', employee_code: 'ORBIT-REP-001', full_name: 'Ishaan Desai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-72', org_id: 'org-4', employee_code: 'ORBIT-REP-002', full_name: 'Kiran Desai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-73', org_id: 'org-4', employee_code: 'ORBIT-REP-003', full_name: 'Amit Patel', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-74', org_id: 'org-4', employee_code: 'ORBIT-REP-004', full_name: 'Aadhya Rao', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-75', org_id: 'org-4', employee_code: 'ORBIT-REP-005', full_name: 'Sunita Mehta', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-76', org_id: 'org-4', employee_code: 'ORBIT-REP-006', full_name: 'Sunita Gupta', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-77', org_id: 'org-4', employee_code: 'ORBIT-REP-007', full_name: 'Rahul Agarwal', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-78', org_id: 'org-4', employee_code: 'ORBIT-REP-008', full_name: 'Aditya Patel', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-79', org_id: 'org-4', employee_code: 'ORBIT-REP-009', full_name: 'Ananya Kapoor', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-80', org_id: 'org-4', employee_code: 'ORBIT-REP-010', full_name: 'Neha Singh', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-81', org_id: 'org-4', employee_code: 'ORBIT-REP-011', full_name: 'Vivaan Kapoor', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-82', org_id: 'org-4', employee_code: 'ORBIT-REP-012', full_name: 'Kiran Gupta', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-83', org_id: 'org-4', employee_code: 'ORBIT-REP-013', full_name: 'Sunita Pillai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-84', org_id: 'org-4', employee_code: 'ORBIT-REP-014', full_name: 'Ananya Menon', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-85', org_id: 'org-4', employee_code: 'ORBIT-REP-015', full_name: 'Reyansh Pillai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-86', org_id: 'org-4', employee_code: 'ORBIT-REP-016', full_name: 'Ramesh Kumar', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-87', org_id: 'org-4', employee_code: 'ORBIT-REP-017', full_name: 'Sanjay Rao', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-88', org_id: 'org-5', employee_code: 'VERTEX-ADM-001', full_name: 'Kavya Iyer', role: 'admin', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-89', org_id: 'org-5', employee_code: 'VERTEX-MGR-001', full_name: 'Myra Bhatt', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-90', org_id: 'org-5', employee_code: 'VERTEX-MGR-002', full_name: 'Aarav Bhatt', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-91', org_id: 'org-5', employee_code: 'VERTEX-MGR-003', full_name: 'Ramesh Patel', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-92', org_id: 'org-5', employee_code: 'VERTEX-REP-001', full_name: 'Ishaan Verma', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-93', org_id: 'org-5', employee_code: 'VERTEX-REP-002', full_name: 'Kiran Gupta', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-94', org_id: 'org-5', employee_code: 'VERTEX-REP-003', full_name: 'Ajay Sharma', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-95', org_id: 'org-5', employee_code: 'VERTEX-REP-004', full_name: 'Swati Singh', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-96', org_id: 'org-5', employee_code: 'VERTEX-REP-005', full_name: 'Anika Kapoor', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-97', org_id: 'org-5', employee_code: 'VERTEX-REP-006', full_name: 'Kiran Gupta', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-98', org_id: 'org-5', employee_code: 'VERTEX-REP-007', full_name: 'Aadhya Pillai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-99', org_id: 'org-5', employee_code: 'VERTEX-REP-008', full_name: 'Vivaan Verma', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-100', org_id: 'org-5', employee_code: 'VERTEX-REP-009', full_name: 'Nisha Rao', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-101', org_id: 'org-5', employee_code: 'VERTEX-REP-010', full_name: 'Shalini Patel', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-102', org_id: 'org-5', employee_code: 'VERTEX-REP-011', full_name: 'Ramesh Bhatt', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-103', org_id: 'org-5', employee_code: 'VERTEX-REP-012', full_name: 'Vivaan Joshi', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-104', org_id: 'org-5', employee_code: 'VERTEX-REP-013', full_name: 'Reyansh Verma', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-105', org_id: 'org-5', employee_code: 'VERTEX-REP-014', full_name: 'Ramesh Iyer', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-106', org_id: 'org-5', employee_code: 'VERTEX-REP-015', full_name: 'Ramesh Sharma', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-107', org_id: 'org-5', employee_code: 'VERTEX-REP-016', full_name: 'Neha Reddy', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-108', org_id: 'org-5', employee_code: 'VERTEX-REP-017', full_name: 'Ananya Patel', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-109', org_id: 'org-6', employee_code: 'PRIME-ADM-001', full_name: 'Ananya Rao', role: 'admin', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-110', org_id: 'org-6', employee_code: 'PRIME-MGR-001', full_name: 'Ananya Sharma', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-111', org_id: 'org-6', employee_code: 'PRIME-MGR-002', full_name: 'Krishna Malhotra', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-112', org_id: 'org-6', employee_code: 'PRIME-MGR-003', full_name: 'Suresh Iyer', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-113', org_id: 'org-6', employee_code: 'PRIME-REP-001', full_name: 'Kiran Iyer', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-114', org_id: 'org-6', employee_code: 'PRIME-REP-002', full_name: 'Ramesh Malhotra', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-115', org_id: 'org-6', employee_code: 'PRIME-REP-003', full_name: 'Sunita Malhotra', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-116', org_id: 'org-6', employee_code: 'PRIME-REP-004', full_name: 'Amit Menon', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-117', org_id: 'org-6', employee_code: 'PRIME-REP-005', full_name: 'Aarav Pillai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-118', org_id: 'org-6', employee_code: 'PRIME-REP-006', full_name: 'Amit Bhatt', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-119', org_id: 'org-6', employee_code: 'PRIME-REP-007', full_name: 'Ramesh Pillai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-120', org_id: 'org-6', employee_code: 'PRIME-REP-008', full_name: 'Reyansh Chopra', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-121', org_id: 'org-6', employee_code: 'PRIME-REP-009', full_name: 'Divya Iyer', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-122', org_id: 'org-6', employee_code: 'PRIME-REP-010', full_name: 'Ananya Patel', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-123', org_id: 'org-6', employee_code: 'PRIME-REP-011', full_name: 'Ananya Nair', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-124', org_id: 'org-6', employee_code: 'PRIME-REP-012', full_name: 'Meera Pillai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-125', org_id: 'org-6', employee_code: 'PRIME-REP-013', full_name: 'Ishaan Desai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-126', org_id: 'org-6', employee_code: 'PRIME-REP-014', full_name: 'Divya Iyer', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-127', org_id: 'org-6', employee_code: 'PRIME-REP-015', full_name: 'Divya Verma', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-128', org_id: 'org-6', employee_code: 'PRIME-REP-016', full_name: 'Ishaan Rao', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-129', org_id: 'org-6', employee_code: 'PRIME-REP-017', full_name: 'Manoj Nair', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-130', org_id: 'org-7', employee_code: 'APEX-ADM-001', full_name: 'Amit Singh', role: 'admin', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-131', org_id: 'org-7', employee_code: 'APEX-MGR-001', full_name: 'Divya Verma', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-132', org_id: 'org-7', employee_code: 'APEX-MGR-002', full_name: 'Suresh Reddy', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-133', org_id: 'org-7', employee_code: 'APEX-MGR-003', full_name: 'Ajay Malhotra', role: 'manager', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-134', org_id: 'org-7', employee_code: 'APEX-REP-001', full_name: 'Krishna Mehta', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-135', org_id: 'org-7', employee_code: 'APEX-REP-002', full_name: 'Deepak Verma', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-136', org_id: 'org-7', employee_code: 'APEX-REP-003', full_name: 'Rahul Mehta', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-137', org_id: 'org-7', employee_code: 'APEX-REP-004', full_name: 'Priya Pillai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-138', org_id: 'org-7', employee_code: 'APEX-REP-005', full_name: 'Rekha Bhatt', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-139', org_id: 'org-7', employee_code: 'APEX-REP-006', full_name: 'Aditya Iyer', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-140', org_id: 'org-7', employee_code: 'APEX-REP-007', full_name: 'Krishna Rao', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-141', org_id: 'org-7', employee_code: 'APEX-REP-008', full_name: 'Priya Reddy', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-142', org_id: 'org-7', employee_code: 'APEX-REP-009', full_name: 'Aadhya Agarwal', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-143', org_id: 'org-7', employee_code: 'APEX-REP-010', full_name: 'Sunita Malhotra', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-144', org_id: 'org-7', employee_code: 'APEX-REP-011', full_name: 'Kavya Mehta', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-145', org_id: 'org-7', employee_code: 'APEX-REP-012', full_name: 'Myra Kapoor', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-146', org_id: 'org-7', employee_code: 'APEX-REP-013', full_name: 'Aadhya Singh', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-147', org_id: 'org-7', employee_code: 'APEX-REP-014', full_name: 'Shalini Chopra', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-148', org_id: 'org-7', employee_code: 'APEX-REP-015', full_name: 'Reyansh Bhatt', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-149', org_id: 'org-7', employee_code: 'APEX-REP-016', full_name: 'Saanvi Malhotra', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
  { id: 'user-150', org_id: 'org-7', employee_code: 'APEX-REP-017', full_name: 'Amit Pillai', role: 'rep', manager_id: null, onboarding_status: 'active', deactivated_at: null, created_at: NOW },
]
