project_id = "iimk-project-sales-agent"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["http://127.0.0.1:5173"]
jwt_expiry = 3600
enable_signup = true

[auth.hook.custom_access_token]
enabled = true
uri = "pg-functions://postgres/public/custom_access_token_hook"

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_OAUTH_CLIENT_ID)"
secret = "env(GOOGLE_OAUTH_CLIENT_SECRET)"

[auth.external.linkedin_oidc]
enabled = true
client_id = "env(LINKEDIN_OAUTH_CLIENT_ID)"
secret = "env(LINKEDIN_OAUTH_CLIENT_SECRET)"

[storage]
enabled = true
file_size_limit = "10MiB"

[functions.employee-login]
verify_jwt = false

[functions.invite-user]
verify_jwt = true
